Class {
	#name : #CZDocumentVisitor,
	#superclass : #Object,
	#instVars : [
		'fileName',
		'lastOutput',
		'outputStream',
		'lastEntryVisited',
		'defaultSeparator',
		'authorDisplay'
	],
	#category : #'Citezen-Outputers'
}

{ #category : #visiting }
CZDocumentVisitor >> visitComment: aCZCommentElement [
	
]

{ #category : #visiting }
CZDocumentVisitor >> visitCompositeValue: aCZCompositeValue [
	
]

{ #category : #visiting }
CZDocumentVisitor >> visitDocument: aCZDocument [
	
]
