Class {
	#name : #CZScriptTest,
	#superclass : #TestCase,
	#instVars : [
		'sc'
	],
	#category : #'Citezen-Scripts'
}

{ #category : #data }
CZScriptTest class >> lseBibSample [
	^ '@book{Abad96a,
  Author       = {Mart{\''\i}n Abadi and Luca Cardelli},
  Isbn	       = {0-387-94775-2},
  Keywords     = {olit oobib(types) scglib ioom-types},
  Publisher    = {Springer-Verlag},
  Title	       = {A Theory of Objects},
  Year	       = {1996}
}


@inproceedings{Abde09b,
  author       = {Hani Abdeen and St\''ephane Ducasse and Houari Sahraoui and Ilham Alloui},
  title	       = {Automatic Package Coupling and Cycle Minimization},
  booktitle    = {International Working Conference on Reverse Engineering (WCRE)},
  publisher    = {IEEE Computer Society Press},
  Misc	       = {acceptance rate: 20/79 = 25\%},
  pages	       = {103--112},
  annote       = {internationalconference},
  misc	       = {Acceptance rate: 25\%},
  aeres	       = {ACT},
  x-pays       = {Canada},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes},
  aeresstatus  = {aeres12},
  rate	       = {25\%},
  selectif     = {oui},
  inria	       = {RMOD},
  keywords     = {moose remoose2 lse-pub cook},
  year	       = {2009}
}

@article{Abde09x,
  title        = {Package Fingerprint: a visual summary of package interfaces and relationships},
  author       = {Hani Abdeen and St\''ephane Ducasse  and Damien Pollet and Ilham Alloui },
  journal      = {Under submission at Information and Software Technology Journal},
  annote       = {internationaljournal},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes},
  keywords     = {moose insubmission lse-pub cook},
  year         = {2009}
}

@inproceedings{Abdi09a,
  author =  {Abdi, Mustapha and Lounis, Hakim and Sahraoui, Houari},
  title  =  {Analyse et pr\''ediction de l''impact de changements dans un syst\`eme \`a objets : Approche probabiliste},
  annote =  {nationalconference},
  booktitle = {Proceedings of LMO''09},
  year = {2009}
}

@book{Acet07a,
  author       = {Aceto, Luca},
  title	       = {Reactive systems},
  publisher    = {lua.org},
  year	       = {2006}
}


@book{Aho86a,
  Address      = {Reading, Mass.},
  Author       = {Alfred V. Aho and Ravi Sethi and Jeffrey D. Ullman},
  Isbn	       = {0-201-10194-7},
  Keywords     = {compiler book binder (shelf) scglib},
  Publisher    = {Addison Wesley},
  Title	       = {Compilers: Principles, Techniques and Tools},
  Year	       = {1986}
}

@article{Alas04a,
    author = {Alastair Farrugia},
    title = {Vertex-partitioning into fixed additive induced-hereditary properties is NP-hard},
    journal = {the electronic journal of combinatorics},
    year = {2004},
    volume = {11}
}

@inproceedings{Allo08a,
    author = {Ilham Alloui and Sorana C{\^i}mpan and Herv{\''e} Verjus},
    title = {Towards Software Architecture Physiology: Identifying Vital Components},
    booktitle    = {Working IEEE/IFIP Conference on Software Architecture (WICSA)},
    year = {2008}
}

@book{Alpe98a,
  Author       = {Sherman R. Alpert and Kyle Brown and Bobby Woolf},
  Isbn	       = {0-201-18462-1},
  Keywords     = {smalltalk patterns scglib oorp},
  Publisher    = {Addison Wesley},
  Title	       = {The Design Patterns {Smalltalk} Companion},
  Year	       = {1998}
}

@inproceedings{Altm08a,
	title = {Models in Conflict - Towards a Semantically Enhanced Version Control System for Models},
	author = {Kerstin Altmanninger},
	series = {LNCS 5002},
	booktitle ={Models in Software Engineering},
	year = {2008}
}


@book{Andr91c,
  Author       = {Gregory R. Andrews},
  Isbn	       = {0-80553-0086-4},
  Publisher    = {The Benjamin Cummings Publishing Co. Inc},
  Title	       = {Concurrent Programming --- Principles and Practice},
  Year	       = {1991}
}

@book{Arms96a,
  Author       = {Joe Armstrong and Robert Virding and Claes Wikstr\"om and Mike Williams},
  Keywords     = {lsebib erlang},
  Publisher    = {Prentice Hall},
  Title	       = {Concurrent Programming in Erlang},
  Year	       = {1996}
}


@inproceedings{Arun08a,
 author = {M. Aruna and M.P. Suguna Devi and M. Deepa},
 title = {Measuring the Quality of Software Modularization Using Coupling-Based Structural Metrics for an OOS System},
 booktitle = {ICETET ''08: Proceedings of the 2008 First International Conference on Emerging Trends in Engineering and Technology},
 year = {2008},
 isbn = {978-0-7695-3267-7},
 pages = {1130--1135},
 doi = {/10.1109/ICETET.2008.76},
 publisher = {IEEE Computer Society},
 address = {Washington, DC, USA}
}



@book{Aste03a,
  Author       = {David Astels},
  Isbn	       = {0-13-101649-0},
  Keywords     = {scglib},
  Publisher    = {Prentice Hall},
  Title	       = {Test-Driven Development --- A Practical Guide},
  Year	       = {2003}}

@inproceedings{Badr05a,
	title={Supporting predictive change impact analysis: a control call graph based technique},
	author={Badri, L. and Badri, M. and St-Yves, D.},
	booktitle={Software Engineering Conference (APSEC ''05)},
	year={2005},
	month={dec},
	pages={9--15},
	doi={10.1109/APSEC.2005.100},
	ISSN={1530-1362}
}

@article{Bahi01a,
 author = {William L. Chapman and Jerzy Rozenblit and A. Terry Bahill},
 title = {System design is an NP-complete problem: Correspondence},
 journal = {Systems Engineering},
 volume = {4},
 number = {3},
 year = {2001},
 issn = {1098-1241},
 pages = {222--229},
 doi = {10.1002/sys.v4:3},
 publisher = {John Wiley and Sons Ltd.},
 address = {Chichester, UK, UK}
}

@techreport{Balm09a,
  author       = {Fran\cc oise Balmas and Alexandre Bergel and Simon Denier and St\''ephane Ducasse and Jannik Laval and Karine Mordal-Manet and Hani Abdeen and Fabrice Bellingard},
  title	       = {Software metric for Java and C++ practices},
  keywords	   = {squale-pub lse-pub deliverable11},
  annote       = {technicalReport},
  institution  = {INRIA Lille Nord Europe},
  year	       = {2009}
}

@book{Batt99a,
	author = {Giuseppe Di Battista and Peter Eades and Roberto Tamassia and Ioannis G. Tollis},
	title = {Algorithms for the Visualization of Graphs},
	publisher = {Prentice Hall},
	year = {1999}
}

@inproceedings{Baue04a,
 author = {Markus Bauer and Mircea Trifu},
 title = {Architecture-Aware Adaptive Clustering of OO Systems},
 booktitle = {CSMR ''04: Proceedings of the Eighth Euromicro Working Conference on Software Maintenance and Reengineering (CSMR''04)},
 year = {2004},
 isbn = {0-7695-2107-X},
 pages = {3-14},
 publisher = {IEEE Computer Society},
 address = {Washington, DC, USA}
}

@book{Beck97a,
  Author       = {Kent Beck},
  Publisher    = {Prentice-Hall},
  Title	       = {{Smalltalk} Best Practice Patterns},
  Year	       = {1997},
  ISBN         = {013476904X 	978-0134769042}
}


@book{BenF08a,
	author = {Ben Fry},
	title = {Visualizing Data},
	publisher = {O''REILLY},
	year = {2008}
}

@misc{Beng00a,
    author = {PerOlof Bengtsson and Nico Lassing and Jan Bosch and Hans van Vliet},
    title = {Analyzing Software Architectures for Modifiability},
    year = {2000}
}

@inproceedings{Berg08c,
  author       = {Alexandre Bergel and St\''ephane Ducasse and Jannik Laval and Romain Peirs},
  title	       = {Enhanced Dependency Structure Matrix for Moose},
  annote       = {internationalworkshop},
  keywords     = {moose},
  AERES        = {missing},
  booktitle    = {FAMOOSr, 2nd Workshop on FAMIX and Moose in Reengineering},
  year	       = {2008},
  x-editorial-board = {yes},
  x-proceedings = {no},
  x-international-audience = {yes},
  aeres        = {COM},
  aeresstatus  = {aeres12},
  selectif     = {non},
  labo         = {dans},
  inria        = {RMOD}
}

@inproceedings{Berg09a,
  author = {Alexandre Bergel},
  title = {Reconciling Method Overloading and Dynamically Typed Scripting Languages},
  annote = {insubmission},
  keywords = {insubmission},
  booktitle = {Proceedings of ECOOP''09},
  year = {2009}
}

@inproceedings{Berg09b,
  author =  {Alexandre Bergel},
  title  =  {Contr\^oler la visibilit\''e des aspects avec Aspectboxes},
  annote =  {nationalconference},
  booktitle = {Proceedings of LMO''09},
  year = {2009},
  aeres = {ACT},
  aeresstatus= {aeres12},
  selectif= {non},
  labo= {dans},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {no},
  inria = {RMOD}
}

@techreport{Berg09c,
  title={SQUALE -- Software QUALity Enhancement},
  author={Alexandre Bergel and Simon Denier and St\''ephane Ducasse and Jannik Laval and Fabrice Bellingard and Philippe Vaillergues and Fran\c coise Balmas and Karine Mordal-Manet},
  booktitle={13th European Conference on Software Maintenance and Reengineering (CSMR)},
  year={2009},
  institution = {INRIA},
  aeres = {COM},
  annote = {presentation},
  keywords = {squale-pub lse-pub},
  aeres = {ACT},
  aeresstatus= {aeres12},
  selectif= {non},
  labo= {dans},
  inria = {RMOD},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}




@inproceedings{Bhat07a,
  author       = {Bhatti, Muhammad Usman and St\''ephane Ducasse},
  title	       = {Surgical Information to Detect Design Problems with
                  MOOSE},
  annote       = {internationalworkshop},
  keywords     = {moose-pub},
  booktitle    = {FAMOOSr, 1st Workshop on FAMIX and Moose in
                  Reengineering},
  url	       = {http://scg.unibe.ch/archive/papers/Bhat07aFamoosRWorkshop.pdf},
  year	       = {2007}
}

@inproceedings{Bhat08a,
  author       = {Bhatti, Muhammad Usman and St\''ephane Ducasse and
                  Awais Rashid},
  title	       = {Aspect Mining in Procedural Object-Oriented Code},
  annote       = {internationalconference shortpaper},
  keywords     = {moose-pub},
  aeres	       = {ACT},
  aeresstatus  = {aeres08},
  selectif     = {non},
  inria	       = {RMOD},
  booktitle    = {International Conference on Program Comprehension (ICPC 2008)},
  url	       = {http://scg.unibe.ch/archive/external/Bhat08a-ICPC2008-AspectMining.pdf},
  year	       = {2008},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}


@inproceedings{Bhat08b,
  author       = {Bhatti, Muhammad Usman and St\''ephane Ducasse and
                  Marianne Huchard},
  title	       = {Reconsidering Classes in Procedural Object-Oriented
                  Code},
  annote       = {internationalconference stefPub},
  keywords     = {moose-pub},
  aeres	       = {ACT},
  aeresstatus  = {aeres08},
  selectif     = {non},
  inria	       = {RMOD},
  booktitle    = {International Conference on Reverse Engineering
                  (WCRE)},
  url	       = {http://scg.unibe.ch/archive/external/Bhat08b-WCRE2008ObjectIdentification.pdf},
  year	       = {2008},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@techreport{Bhat08c,
  author       = {Bhatti, Muhammad Usman and St\''ephane Ducasse and
                  Awais Rashid},
  title	       = {Aspect Mining in Procedural Object-Oriented Code},
  url	       = {Bhat08c-AspectMining.pdf},
  annote       = {technicalreport},
  institution  = {INRIA Lille Nord Europe},
  year	       = {2008}
}


@book{Bind99a,
  Author       = {Binder, Robert V.},
  Keywords     = {oobib scglib olit selit testing oorp},
  Location     = {Archiv SCG},
  Publisher    = {Addison Wesley},
  Series       = {Object Technology Series},
  Title	       = {{Testing Object-Oriented Systems: Models, Patterns, and Tools}},
  Year	       = {1999}
}

@book{Bish03a,
  Author       = {Matt Bishop},
  Isbn         = {0-201-44099-7},
  Keywords     = {Security bible},
  Title        = {Computer Security: Art and Science},
  Publisher    = {Pearson Education (Singapore) Pte. Ltd.},
  Year         = {2003}
}

@book{Bish03b,
	author = {Bishop, Matt},
	title = {Clustering for data mining},
	publisher = {Addison-Wesley},
	year = {2003}
}

@book{Blac07a,
  Title	       = {Squeak by Example},
  Author       = {Andrew Black and St\''ephane Ducasse and Oscar
                  Nierstrasz and Damien Pollet and Damien Cassou and
                  Marcus Denker},
  Note	       = {http://SqueakByExample.org/  ordered but not received},
  Publisher    = {Square Bracket Associates},
  Year	       = {2007},
  aeres	       = {OV},
  aeresstatus  = {2008},
  inria	       = {RMOD},
  Abstract     = {Squeak by Example, intended for both students and
                  developers, will guide you gently through the Squeak
                  language and environment by means of a series of
                  examples and exercises. This book is made available
                  under the Creative Commons Attribution-ShareAlike
                  3.0 license.},
  ISBN	       = {978-3-9523341-0-2},
  annote       = {book},
  Url	       = {http://SqueakByExample.org/index.html},
  Keywords     = {skipdoi remoose1-pub}
}



@book{Blac09a,
  Title	       = {Pharo by Example},
  Author       = {Andrew Black and St\''ephane Ducasse and Oscar
                  Nierstrasz and Damien Pollet and Damien Cassou and
                  Marcus Denker},
  Note	       = {http://SqueakByExample.org/  ordered but not received},
  Publisher    = {Square Bracket Associates},
  Year	       = {2009},
  aeres	       = {OV},
  aeresstatus  = {2012},
  annote       = {book},
  inria	       = {RMOD},
  Keywords     = {skipdoi remoose2-pub pharo-pub},
  Abstract     = {Pharo by Example, intended for both students and
                  developers, will guide you gently through the Pharo open-source Smalltalk language and environment by means of a series of
                  examples and exercises. This book is made available
                  under the Creative Commons Attribution-ShareAlike
                  3.0 license.},
  ISBN	       = {978-3-9523341-4-0},
  x-scientific-popularization = {yes}
}


@inproceedings{Bria02e,
 author = {Brian S. Mitchell and Spiros Mancoridis},
 title = {Using Heuristic Search Techniques To Extract Design Abstractions From Source Code},
 booktitle = {Proceedings of GECCO''02},
 year = {2002},
 isbn = {1-55860-878-8},
 pages = {1375--1382},
 publisher = {Morgan Kaufmann Publishers Inc.},
 address = {San Francisco, CA, USA}
}



@inproceedings{Bria03a,
    author = {Brian S. Mitchell},
    title = {A Heuristic Approach to Solving the Software Clustering Problem},
    booktitle = {ICSM ''03: Proceedings of the International Conference on Software Maintenance},
    year = {2003},
    isbn = {0-7695-1905-9},
    pages = {285},
    publisher = {IEEE Computer Society},
    address = {Washington, DC, USA},
    keywords = {Bunch}
}

@article{Bria08a,
 author = {Brian S. Mitchell and Spiros Mancoridis},
 title = {On the evaluation of the Bunch search-based software modularization algorithm},
 journal = {Soft Computing - A Fusion of Foundations, Methodologies and Applications},
 volume = {12},
 number = {1},
 year = {2008},
 issn = {1433-7479},
 pages = {77--93},
 doi = {10.1007/s00500-007-0218-3},
 publisher = {Springer Berlin / Heidelberg},
 address = {Berlin}
}

@book{Call05a,
	author = {Werner Callebaut and Diego Rasskin-Gutman},
	title = {Modularity: Understanding the Development and Evolution of Natural Complex Systems},
	publisher = {MIT press},
	year = {2005}
}

@inproceedings{Casa09a,
  title = {Object Spaces for Safe Image Surgery},
  author = {Gwena{\"e}l Casaccio and Damien Pollet and Marcus Denker and St{\''e}phane Ducasse},
  booktitle = {Proceedings of ESUG International Workshop on Smalltalk Technologies (IWST 2009)},
  year = {2009},
  aeres = {ACT},
  aeresstatus = {aeres12},
  selectif = {non},
  labo = {dans},
  publisher = {ACM digital library},
  inria= {RMOD},
  keywords = {remoose2-pub},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@article{Chun06a,
 author = {Chung-Horng Lung and Xia Xu and Marzia Zaman and Anand Srinivasan},
 title = {Program restructuring using clustering techniques},
 journal = {J. Syst. Softw.},
 volume = {79},
 number = {9},
 year = {2006},
 issn = {0164-1212},
 pages = {1261--1279},
 doi = {10.1016/j.jss.2006.02.037},
 publisher = {Elsevier Science Inc.},
 address = {New York, NY, USA}
}

@inproceedings{Cimp07a,
 author = {Cristina Videira Lopes and Sushil Krishna Bajracharya},
 title = {Dynamic architecture based evolution of enterprise information systems},
 booktitle = {International Conference on Enterprise Information Systems (ICEIS)},
 year = {2007}
}

@inproceedings{Cimp07b,
 	author ={Sorana C\^impan and Herve Verjus and Ilham Alloui},
	title = {Dynamic Architecture based Evolution of Enterprise Information Systems},
	booktitle = {9th Int. Conf. on Enterprise Information Systems},
	pages = {221-229},
	year = {2007}
}

@inproceedings{Cimp08a,
	author ={Sorana C\^impan and Vincent Couturier},
	title = {Can Styles Improve Architectural Pattern Reuse?},
	booktitle = {WICSA},
	year = {2008}
}


@article{Cimp09a,
	author       = {Sorana C{\^\i}mpan and Herv{\''e} Verjus and Ilham Alloui},
	title       = {Gestion de l''\''evolution dans le cadre d''une approche d''ing\''enierie logicielle centr\''ee architecture},
   journal    = {Technique et Science Informatiques (TSI)},
   year        = {2009}
}

@inproceedings{Clar03a,
    author = {John Clarke and Jose Javier Dolado and Mark Harman and Bryan Jones and Mary Lumkin and Brian Mitchell and Kearton Rees and Marc Roper},
    title = {Reformulating software engineering as a search problem},
    booktitle = {IEEE Proceedings on Software},
    volume = {3},
    numero = {150},
    pages = {161-175},
    year = {2003},
    Keywords = {Simulated-Annealing Evolutive-Algorithms Metaheuristic-Algorithms}
}

@book{Crai00a,
 author = {Iain Craig},
 title = {The  Integration of Object-Oriented Programming Languages},
 year = {2000},
 isbn = {1852331593},
 publisher = {Springer-Verlag},
 address = {London, UK}
}

@book{Crai02a,
  author = {Craig and Lain},
  title = {The Interpretation of object-oriented programming languages},
  publisher = {O''Reilly},
  year = {2006}
}

@inproceedings{Cuts09a,
  Author = {van Cutsem, Tom and Alexandre Bergel and St\''ephane Ducasse and De Meuter, Wolfgang},
  booktitle = {Proceedings of ECOOP 2009},
  keywords = {traits alexPub stefPub},
  editor   = {Sophia Drossopoulou},
  publisher    = {Springer},
  x-pays = {Belgium},
  annote = {internationalconference topconference},
  series       = {Lecture Notes in Computer Science},
  title	       = {Adding State and Visibility Control to Traits using Lexical Nesting},
  year	       = {2009},
  url = {http://rmod.lille.inria.fr/Archive/Papers/Cuts09TraitsAmbientTalk.pdf},
  aeres = {ACT},
  aeresstatus = {aeres12},
  selectif = {oui},
  rate = {18%},
  labo = {dans},
  inria = {RMOD},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@misc{DSM,
  title={The Design Structure Matrix (DSM)},
  author={http://www.dsmweb.org}
}

@inproceedings{DeLa98a,
  Author       = {David E. DeLano and Linda Rising},
  Booktitle    = {Pattern Languages of Program Design 3},
  Editor       = {Robert Martin and Dirk Riehle and Frank Buschmann},
  Keywords     = {olit patterns oorp},
  pages	       = {503--527},
  Publisher    = {Addison-Welsey},
  Title	       = {Patterns for System Testing},
  Year	       = {1998},
  ISBN = {0201310112  		978-0201310115},
   Note 	= {ordered but not received}
}

@inproceedings{DeLa98b,
  Author       = {David E. DeLano and Linda Rising},
  Booktitle    = {Pattern Languages of Program Design 2},
  Editor       = {Robert Martin and Dirk Riehle and Frank Buschmann},
  pages	       = {503--527},
  Publisher    = {Addison-Welsey},
  Title	       = {Patterns for System Testing},
  Year	       = {1998},
  ISBN 		= { 0201895277		978-0201895278},
   Note 	= {ordered but not received}
}

@inproceedings{DeLa98c,
  Author       = {David E. DeLano and Linda Rising},
  Booktitle    = {Pattern Languages of Program Design 1},
  Editor       = {Robert Martin and Dirk Riehle and Frank Buschmann},
  pages	       = {503--527},
  Publisher    = {Addison-Welsey},
  Title	       = {Patterns for System Testing},
  Year	       = {1998},
  ISBN 		= { 0201607344		978-0201607345},
   Note 	= {ordered but not received}
}

@inproceedings{DeLa98d,
  Author       = {David E. DeLano and Linda Rising},
  Booktitle    = {Pattern Languages of Program Design 4},
  Editor       = {Robert Martin and Dirk Riehle and Frank Buschmann},
  pages	       = {503--527},
  Publisher    = {Addison-Welsey},
  Title	       = {Patterns for System Testing},
  Year	       = {1998},
  ISBN 		= { 0201433044		978-0201433043},
   Note 	= {ordered but not received}
}

@inproceedings{DeLa98e,
  Author       = {David E. DeLano and Linda Rising},
  Booktitle    = {Pattern Languages of Program Design 5},
  Editor       = {Robert Martin and Dirk Riehle and Frank Buschmann},
  pages	       = {503--527},
  Publisher    = {Addison-Welsey},
  Title	       = {Patterns for System Testing},
  Year	       = {1998},
  ISBN 		= { 0321321944		978-0321321947},
   Note 	= {ordered but not received}
}

@book{Deme02a,
  Abstract     = {The rapid growth of object-oriented development over
                  the past twenty years has given rise to many
                  object-oriented systems that are large, complex and
                  hard to maintain. Object-Oriented Reengineering
                  Patterns addresses the problem of understanding and
                  reengineering such object-oriented legacy
                  systems. This book collects and distills successful
                  techniques in planning a reengineering project,
                  reverse-engineering, problem detection, migration
                  strategies and software redesign. The material in
                  this book is presented as a set of "reengineering
                  patterns" --- recurring solutions that experts apply
                  while reengineering and maintaining object-oriented
                  systems. The principles and techniques described in
                  this book have been observed and validated in a
                  number of industrial projects, and reflect best
                  practice in object-oriented reengineering.},
  Annote       = {book},
  Author       = {Serge Demeyer and St{\''e}phane Ducasse and Oscar
                  Nierstrasz},
  Isbn	       = {1-55860-639-4},
  Keywords     = {olit scg-pub skipdoi jb02 patterns reeng snf02
                  stefPub moose-pub},
  Publisher    = {Morgan Kaufmann},
  Title	       = {Object-Oriented Reengineering Patterns},
  Url	       = {http://www.iam.unibe.ch/~scg/OORP},
  Year	       = {2002}
}

@inproceedings{Deni09a,
  title  = {Understanding the Use of Inheritance with Visual Patterns},
  author = {Simon Denier and Houari Sahraoui},
  booktitle = {Proceedings of the 3rd International Symposium on Empirical Software Engineering and Measurement (ESEM 2009)},
  editor = {James Miller and Rick Selby},
  publisher = {IEEE Computer Society Press},
  OPTpages = {??--??},
  year = {2009},
  keywords = {lse-pub},
  annote       = {internationalconference},
  aeres = {ACT},
  aeresstatus = {aeres12},
  selectif = {non},
  labo= {hors},
  rate = {39%},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@inproceedings{Deni09b,
  title  = {Proposals for the Reborn Pharo Developer},
  author = {Simon Denier and Damien Pollet and St\''ephane Ducasse},
  booktitle = {Proceedings of ESUG International Workshop on Smalltalk Technologies (IWST 2009)},
  year = {2009},
  keywords = {lse-pub pharo-pub},
  annote       = {internationalworkshop},
  aeres = {ACT},
  aeresstatus = {aeres12},
  selectif = {non},
  labo= {dans},
  inria = {rmod},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@proceedings{Deni09c,
  title = {Proceedings of the 3rd Workshop on FAMIX and MOOSE in Software Reengineering (FAMOOSr 2009)},
  editor = {Simon Denier and Tudor Gi\^irba},
  year = {2009},
  keywords = {moose-pub lse-pub},
  annote = {workshopproceedings},
  aeres = {AP},
  aeresstatus = {aeres12},
  labo= {dans},
  inria = {rmod},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@book{Deo74a,
  title={Graph Theory with Applications to Engineering and Computer Science},
  author={Deo, N.},
  year={1974},
  publisher={Prentice-Hall, Inc. Upper Saddle River, NJ, USA}
}

@article{Desm08a,
	author = {Desmet, Lieven and Verbaeten, Petrus and Joosen, Wouter and Piessens, Frank},
	title = {Provable protection against web application vulnerabilities related to session data dependencies},
	journal = {IEEE transactions on software engineering},
	year = {2008},
	month = jan,
	volume = {34},
	number = {1},
	pages = {50--64},
	url = {https://lirias.kuleuven.be/handle/123456789/161855},
	doi = {10.1109/TSE.2007.70742},
	issn = {0098-5589}
}

@article{Dig08a,
  author = {Danny Dig and Kashif Manzoor and Ralph johnson and Tien N. Nguyen},
  journal = {Transactions of Software Engineering},
  year = {2008},
  title = {Effective Software Merging in the Presence of Object-Oriented Refactorings},
  month = jun,
  volume = {34},
  number = {3}
}

@inproceedings{Dova99c,
 author = {D. Doval and S. Mancoridis and B. S.Mitchell},
 title = {Automatic Clustering of Software Systems Using a Genetic Algorithm},
 booktitle = {STEP ''99: Proceedings of the Software Technology and Engineering Practice},
 year = {1999},
 isbn = {0-7695-0328-4},
 pages = {73},
 publisher = {IEEE Computer Society},
 address = {Washington, DC, USA}
}

@book{Dowd07a,
	author = {Dowd and Mark},
	title = {Art of software security assessment},
	publisher = {Addison-Wesley},
	year = {2007},
	note = {received, Suen}
}

@article{Duca08a,
  Annote       = {internationaljournal},
  Author       = {St\''ephane Ducasse and Tudor G\^irba and Adrian Kuhn and Lukas Renggli},
  Journal      = {Journal of Software and Systems Modeling (SOSYM)},
  Publisher    = {Springer Verlag},
  Title	       = {Meta-Environment and Executable Meta-Language using
                  {Smalltalk}: an Experience Report},
  aeres	       = {ACL},
  x-pays       = {Switzerland},
  selectif     = {oui},
  labo         = {dans},
  inria	       = {RMOD},
  annote       = {internationaljournal cook-pub remoose1-pub},
  url	       = {http://scg.unibe.ch/archive/drafts/Duca08a-Sosym-ExecutableMetaLanguage.pdf},
  doi = {10.1007/s10270-008-0081-4},
  month = feb,
  number = {1},
  pages = {5--19},
	volume = {8},
	year = {2009},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@inproceedings{Duca09a,
  author       = {Ducasse, St\''ephane and Pollet, Damien and Bergel,
                  Alexandre and Cassou, Damien},
  title	       = {Reusing and Composing Tests with Traits},
  booktitle    = {Proceedings of the 47th International Conference
                  Objects, Models, Components, Patterns
                  (TOOLS-Europe''09)},
  hal 	       = {http://hal.archives-ouvertes.fr/docs/00/40/35/68/PDF/Reusing_Composing.pdf},
  year	       = {2009},
  keywords     = {tools09 traits stefPub},
  month	       = {jun},
  annote       = {internationalconference},
  aeres	       = {ACL},
  aeresstatus  = {aeres12},
  selectif     = {oui},
  rate         = {24%},
  labo         = {dans},
  inria	       = {RMOD},
  pages	       = {252--271},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@inproceedings{Duca09b,
  author       = {Ducasse, St\''ephane and Denker, Marcus and Lienhard, Adrian},
  title	       = {Evolving a Reflective Language},
  booktitle    = {Proceedings of the International Workshop on Smalltalk Technologies (IWST 2009)},
  year	       = {2009},
  keywords     = {stefPub internationalworkshop},
  month	       = {jun},
  annote       = {internationalworkshop},
  aeres        = {ACT},
  x-pays       = {Chile, Switzerland},
  aeresstatus  = {aeres12},
  selectif     = {non},
  labo         = {dans},
  inria	       = {RMOD},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@article{Duca09c,
  Abstract     = {To maintain and understand large applications, it is
                  crucial to know their architecture. The first
                  problem is that unlike classes and packages,
                  architecture is not explicitly represented in the
                  code. The second problem is that successful
                  applications evolve over time, so their architecture
                  inevitably drifts. Reconstructing the architecture
                  and checking whether it is still valid is therefore
                  an important aid. While there is a plethora of
                  approaches and techniques supporting architecture
                  reconstruction, there is no comprehensive state of
                  the art and it is often difficult to compare the
                  approaches. This article presents a state of the art
                  in software architecture reconstruction approaches.},
  Annote       = {internationaljournal},
  Author       = {Ducasse, St\''ephane and Pollet, Damien},
  Journal      = {IEEE Transactions on Software Engineering},
  volume = 35,
  number = 4,
  aeres	       = {ACL},
  aeresstatus  = {aeres12},
  selectif     = {oui},
  inria	       = {RMOD},
  labo         = {dans},
  Title	       = {Software Architecture Reconstruction: A Process-Oriented Taxonomy},
 url	       = {http://scg.unibe.ch/archive/external/Duca09x-SOAArchitectureExtraction.pdf},
  Year	       = {2009},
  Month = jul,
  pages = {573-591},
  doi = {10.1109/TSE.2009.19},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@techreport{Duca09d,
  author       = {St\''ephane Ducasse and Simon Denier and Fran\cc oise Balmas and Alexandre Bergel and Jannik Laval and Karine Mordal-Manet and Fabrice Bellingard},
  title	       = {Software metric for Java and C++ practices},
  keywords	   = {squale-pub lse-pub deliverable12},
  annote       = {technicalReport},
  institution  = {INRIA Lille Nord Europe},
  year	       = {2009}
}

@book{Duca09f,
  Title	       = {Dynamic Web Development with Seaside},
  Author       = {St\''ephane Ducasse and Lukas Renggli and David C. Shaffer and Rick Zaccone and Michael Davies},
  url	       = {http://book.seaside.st/},
  Year	       = {2009},
  keywords     = {remoose2-pub},
  aeres	       = {OV},
  x-pays       = {USA, Switzerland},
  aeresstatus  = {2012},
  annote       = {book},
  inria	       = {RMOD},
  publisher    = {Square Bracket Associates},
  Keywords     = {skipdoi remoose2-pub pharo-pub},
   x-scientific-popularization = {yes}
}

@article{Duca09z,
  title = {Understanding Packages: The Package Blueprint},
  author       = {St\''ephane Ducasse  and Hani Abdeen and Damien Pollet and Mathieu Suen and Ilham Alloui},
  journal	   = {Under submission at the IEEE Transactions on Software Engineering (TSE) Journal},
  annote       = {internationaljournal},
  keywords     = {under-submission sub},
  year	= {2009},
  month = aug
}

@inproceedings{Edwi02c,
 author = {Edwin Hautus},
 title = {Improving Java Software through Package Structure Analysis},
 booktitle = {Software Engineering and Applications - 2002},
 year = {2002},
 publisher = {ACTA Press},
 address = {Calgary, AB, Canada}
}

@article{Elba03a,
  author = {S. Elbaum  and   P. Kallakuri and Malishevsky, A. G. and Rothermel, G. and Kanduri, S.},
  title = {Understanding the effects of changes on the cost-effectiveness of regression testing techniques},
  journal = {Journal of Software Testing, Verification, and Reliability},
  year = {2003}
}


@book{Evan03a,
 author = {Eric Evans},
 title = {Domain-Driven Design: Tacking Complexity In the Heart of Software},
 year = {2003},
 isbn = {0321125215},
 publisher = {Addison-Wesley Longman Publishing Co., Inc.},
 address = {Boston, MA, USA},
   Note 	= {ordered but not received}
}

@book{Evan04a,
	author = {Evans and Eric},
	title = {Domain-driven design},
	publisher = {Addison-Wesley},
	year = {2004}
}

@book{Fent96a,
  Address      = {London, UK},
  Author       = {Norman Fenton and Shari Lawrence Pfleeger},
  Edition      = {Second},
  Isbn	       = {0534956009},
  Keywords     = {metrics oorp scglib},
  Publisher    = {International Thomson Computer Press},
  Title	       = {Software Metrics: {A} Rigorous and Practical
                  Approach},
  Year	       = {1996},
  note = {06-8147-I*, envoye a l''inria lille le 19 aout}
}

@misc{Ferl01c,
 author = {Jacques A. Ferland and Daniel Costa},
 title = {Heuristic Search Methods for Combinatorial Programming Problems},
 url	= {http://www.iro.umontreal.ca/~ferland/Genetic/Heur_Search_Methods_Ferland_Costa.pdf},
 year	 = {2001}
}

@book{Few06a,
	Author = {S. Few},
	Title = {Information Dashboard Design},
	Publisher = {OReilly},
	ISBN = {0596100167 978-0596100162},
	Year = {2006}
}

@book{Fowl99a,
  Author       = {Martin Fowler and Kent Beck and John Brant and
                  William Opdyke and Don Roberts},
  Keywords     = {olit patterns famoos refactoring oorp scglib},
  Publisher    = {Addison Wesley},
  Title	       = {Refactoring: Improving the Design of Existing Code},
  Year	       = {1999},
   Note 	= {ordered but not received}
}

@book{Frie01a,
 author = {Daniel P. Friedman and Christopher T. Haynes and Mitchell Wand},
 title = {Essentials of programming languages (2nd ed.)},
 year = {2001},
 isbn = {0-262-06217-8},
 publisher = {Massachusetts Institute of Technology},
 address = {Cambridge, MA, USA}
}

@inproceedings{Geba91a,
  title={Methods For Analyzing Design Procedures},
  author={Gebala, D.A. and Eppinger, S.D. and Cambridge, M.},
  booktitle={3rd International Conference on Design Theory and Methodology},
  year={1991},
  publisher={Amer Society of Mechanical}
}

@book{Gilb05a,
 author = {Tom Gilb},
 title = {Competitive Engineering: A Handbook For Systems Engineering, Requirements Engineering, and Software Engineering Using Planguage},
 year = {2005},
 isbn = {0750665076},
 publisher = {Butterworth-Heinemann},
 address = {Newton, MA, USA}
}

@book{Golu80a,
	author = {Martin Charles Golumbic},
	title = {Algorithmic Graph Theory and Perfect Graphs},
	publisher = {Academic Press},
	year = {2004}
}

@book{Goos94a,
  Author       = {Michael Goossens and Frank Mittelbach and Alexander Samarin},
  Isbn	       = {0-201-54199-8},
  Keywords     = {scglib},
  Publisher    = {Addison Wesley},
  Title	       = {The Latex Companion},
  Year	       = {1994},
   Note 	= {ordered but not received}
}

@book{Goos97a,
	Author = {Michel Goossens and Sebastian Rahtz and Frank Mittelbach},
	Title = {The LaTeX Graphics Companion: Illustrating Documents with TeX and Postscript(R) (Tools and Techniques for Computer Typesetting)},
	ISBN = {0321508920 978-0321508928},
	Publisher = {Addison-Wesley},
	Year = {2007},
   Note 	= {ordered but not received}
}

@article{Gris93d,
 author = {William G. Griswold and David Notkin},
 title = {Automated assistance for program restructuring},
 journal = {ACM Trans. Softw. Eng. Methodol.},
 volume = {2},
 number = {3},
 year = {1993},
 issn = {1049-331X},
 pages = {228--269},
 doi = {10.1145/152388.152389},
 publisher = {ACM},
 address = {New York, NY, USA}
}

@book{Gros04a,
	author = {Gross},
	title = {Handbook of graph theory},
	publisher = {CRC Press},
	year = {2004}
}

@book{Grub05a,
	author = {Penny Grubb and Armstrong A. Takang},
	title = {Software Maintenance Concepts and Practices},
	edition = {second edition},
	publisher = {World Scientific},
	year = {2005}
}

@book{Hari04a,
	author = {P. Van Roy and S. Haridi},
	title = {Concepts, Techniques and models of computer programming},
	publisher = {MIT PRESS},
	year = {2004},
	note = {received, library}
}

@article{Harm01b,
    title = {An overview of program slicing},
    address = {Department of Information Systems and Computing, Brunel University, Uxbridge, Middlesex, UB8 3PH, UK},
    author = {Harman Mark  and Hierons Robert},
    doi = {10.1002/swf.41},
    journal = {Software Focus},
    keywords = {slicing},
    number = {3},
    pages = {85--92},
    volume = {2},
    year = {2001}
}

@inproceedings{Harm02a,
    author = {Mark Harman and Robert Hierons and Mark Proctor},
    title = {A new representation and crossover operator for search-based optimization of software modularization},
    booktitle = {In GECCO 2002: Proceedings of the Genetic and Evolutionary Computation Conference},
    year = {2002},
    pages = {1351--1358},
    publisher = {Morgan Kaufmann Publishers},
    Keywords = {Evolutive-Algorithms Genetic-Algorithms  Subsystem-Decomposition Subsystem-Improvement}
}

@inproceedings{Harm07f,
  author = {Mark Harman and Laurence Tratt},
  title = {Pareto Optimal Search Based Refactoring at the Design Level},
  booktitle = {Proceddings of GECCO''07},
  year = {2007},
  pages = {1106-1113}
}

@inproceedings{Harp94a,
 author = {Harpal Maini and Kishan Mehrotra and Chilukuri Mohan and Sanjay Ranka},
 title = {Genetic algorithms for graph partitioning and incremental graph partitioning},
 booktitle = {Supercomputing ''94: Proceedings of the 1994 conference on Supercomputing},
 year = {1994},
 isbn = {0-8186-6605-6},
 pages = {449--457},
 location = {Washington, D.C., United States},
 publisher = {IEEE Computer Society Press},
 address = {Los Alamitos, CA, USA}
}

@book{Harr99a,
 author = {Robert L. Harris},
 title = {Information Graphics: A Comprehensive Illustrated Reference},
 year = {1999},
 isbn = {0195135326},
 publisher = {Oxford University Press, Inc.},
 address = {New York, NY, USA}
}

@book{Hend96a,
  Author       = {Brian Henderson-Sellers},
  Isbn	       = {0-13-239872-9},
  Keywords     = {olit scglib},
  Publisher    = {Prentice-Hall},
  Title	       = {Object-Oriented Metrics: Measures of Complexity},
  Year	       = {1996}
}

@book{IEEE96a,
	 editor = {IEEE},
	title = {Software Change Impact Analysis (Practitioners) (Paperback)},
	publisher = {Wiley-IEEE Computer Society Pr},
	year = {1996}
}

@article{Jarv02a,
	author = {Kalervo J{\"a}rvelin and Jaana Kek{\"a}l{\"a}inen},
	title = {Cumulated Gain-Based Evaluation of IR Techniques},
	journal = {ACM Transactions on Information Systems},
	volume = 20,
	number = 4,
	year = {2002},
	pages = {422--446}
}

@book{Jeze96a,
  Author       = {J-M. J\''ez\''equel},
  Isbn	       = {0-201-63381-7},
  Keywords     = {olit-oopl scglib},
  Publisher    = {Addison Wesley},
  Title	       = {Object-Oriented Software Engineering with Eiffel},
  Year	       = {1996}
}

@book{Jone96a,
author = {Richard Jones},
title = {Garbage Collection: Algorithms for Automatic Dynamic Memory Management},
month = jul,
year = {1996},
pages = {403},
keywords = {garbage collection},
url = {http://www.cs.kent.ac.uk/pubs/1996/13},
ISBN = {0--471--94148--4},
publisher = {John Wiley and Sons}
}

@book{Kan03a,
	author = {Kan, Stephen H.},
	title = {Metrics and models in software quality engineering},
	publisher = {O''Reilly},
	year = {2006}
}

@book{Kave06a,
	author = {Kaveh},
	title = {Optimal structural analysis},
	publisher = {Wiley},
	year = {2006}
}

@article{Keef06c,
author = {Mark O''Keeffe and Mel \''{\O}Cinn\''{e}ide},
title = {Search-Based Software Maintenance},
journal ={European Conference on Software Maintenance and Reengineering},
volume = {0},
year = {2006},
issn = {1052-8725},
pages = {249-260},
doi = {10.1109/CSMR.2006.49},
publisher = {IEEE Computer Society},
address = {Los Alamitos, CA, USA}
}

@article{Keef07c,
 author = {Mark O''Keeffe and Mel \''{\O} Cinn\''{e}ide},
 title = {Search-based refactoring for software maintenance},
 journal = {Journal of Systems and Software},
 volume = {81},
 number = {4},
 year = {2008},
 issn = {0164-1212},
 pages = {502--516},
 doi = {/10.1016/j.jss.2007.06.003},
 publisher = {Elsevier Science Inc.},
 address = {New York, NY, USA}
}

@book{Kent06a,
 author = {Kent Beck},
 title = {Implementation Patterns},
 year = {2006},
 isbn = {0321413091},
 publisher = {Addison-Wesley Professional}
}

@book{Keri04a,
 author = {Joshua Kerievsky},
 title = {Refactoring to Patterns},
 year = {2004},
 isbn = {0321213351},
 publisher = {Pearson Higher Education}
}

@book{Kicz91a,
  Author       = {Gregor Kiczales and Jim des Rivi\`eres and Daniel
                  G. Bobrow},
  Isbn	       = {0-262-11158-6},
  Publisher    = {MIT Press},
  Title	       = {The Art of the Metaobject Protocol},
  Year	       = {1991}
}

@article{Kirk83a,
 author = {S. Kirkpatrick and C. D. Gelatt Jr. and M. P. Vecchi},
 title = {Optimization by Simulated Annealing},
 journal = {Science},
 volume = {220},
 number = {4598},
 year = {1983},
 pages = {671--680},
 doi = {10.1126/science.220.4598.671}
}

@book{Koch03a,
	Author = {Stephen G. Kochan},
	ISBN = {0672325861},
	Title = {Programming in Objective-C (Developer''s Library)},
	Year = {2003},
	Publisher = {Sams}
}

@book{Kopk99a,
  Author       = {Helmut Kopka and Patrick W. Daly},
  Isbn	       = {0-201-39825-7},
  Keywords     = {scglib},
  Publisher    = {Addison Wesley},
  Title	       = {A Guide To Latex},
  Year	       = {1999}
}

@book{Kozo02a,
	author = {Kozo Sugiyama},
	title = {Graph Drawing and Applications for Software and Knowledge Engineers},
	publisher = {World Scientific},
	year = {2002},
	note = {received 10-06-2009}
}

@inproceedings{Kung94a,
   author = {D. Kung and J. Gao and P. Hsia and F. Wen and Y. Toyoshima, Y. and C. Chen},
   title = {Change impact identification in object oriented software maintenance},
   booktitle= {Proceedings of the International Conference on Software Maintenance},
  year = {1994},
   pages = {202--211}}

@book{Lanz06a,
  Author       = {Michele Lanza and Radu Marinescu},
  Isbn	       = {3-540-24429-8},
  Keywords     = {metrics norex06},
  Publisher    = {Springer-Verlag},
  Title	       = {Object-Oriented Metrics in Practice},
  Url	       = {http://www.springer.com/alert/urltracking.do?id=5907042},
  Year	       = {2006}
}

@book{Larm98a,
  Author       = {Craig Larman},
  Keywords     = {uml book scglib},
  Publisher    = {Prentice-Hall},
  Title	       = {Applying {UML} and Patterns, An Introduction to Object-Oriented Analysis and Design},
  Year	       = {1998}
}

@inproceedings{Laut09a,
  Title	       = {Meteoroid Towards a real MVC for the Web},
  Abstract     = {Web development has moved from simple static pages to complex web applications, some of them
resembling desktop ones. In most of these applications the web browser acts as thin-client (or a view) of the
model that sits on the server. Despite the technological evolution of the web, there is still no standard
mechanism to send data or events from the server to the client without an explicit request from the later,
thus forcing the web browser to constantly poll the server for updates. To solve this problem a set of
techniques under the name of Comet were proposed, allowing to send information from the server to the web
browser without an explicit client request. In this paper we introduce Meteoroid, a Comet approach to make
live Seaside applications. Our framework exploits the Model-View-Controller (MVC) paradigm for building
 simple yet scalable web applications, requiring very little programming effort.},
  Annote       = {internationalworkshop},
  Author       = {Juan Lautaro Fern\''andez and Santiago Robles	and Andr\''es Fortier and Ste\''phane Ducasse
and Gustavo Rossi and 	Silvia Gordillo},
  Booktitle    = {Proceedings of International Workshop on Smalltalk Technologies (IWST 2009)},
  Peer	       = {yes},
  x-pays       = {Argentina},
  Keywords     = {stefPub},
  Location     = {Brest, France},
  Publisher    = {ACM Digital Library},
  Year	       = {2009},
  Note	    = {To appear},
  aeres	       = {ACT},
  aeresstatus  = {aeres12},
  selectif     = {non},
  inria	       = {RMOD},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@inproceedings{Lava08a,
  author       = {Jannik Laval and Alexandre Bergel and St\''ephane Ducasse},
  title	       = {Assessing the Quality of your Software with MoQam},
  annote       = {internationalworkshop},
  keywords     = {moose-pub stefPub},
  booktitle    = {FAMOOSr, 2nd Workshop on FAMIX and Moose in Reengineering},
  year	       = {2008},
  x-editorial-board = {yes},
  x-proceedings = {no},
  x-international-audience = {yes}
}

@inproceedings{Lava09a,
  title      = {Matrice de d\''ependances enrichie},
  author     = {Jannik Laval and Alexandre Bergel and St\''ephane Ducasse},
  booktitle  = {Proceedings of Languages et Mod\`eles \`a Objets (LMO 2009)},
  annote     = {nationalconference},
  year       = {2009},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {no}
}

@inproceedings{Lava09b,
  title  = {Supporting Incremental Changes in Large Models},
  author = {Jannik Laval and Simon Denier and St\''ephane Ducasse and Andy Kellens},
  booktitle = {Proceedings of ESUG International Workshop on Smalltalk Technologies (IWST 2009)},
  year = {2009},
  keywords     = {moose-pub lse-pub},
  annote       = {internationalworkshop},
  aeres = {ACT},
  x-pays = {Belgium},
  aeresstatus = {aeres12},
  selectif = {oui},
  inria= {dans},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@inproceedings{Lava09c,
  title = {Identifying cycle causes with Enriched Dependency Structural Matrix},
  author = {Jannik Laval and Simon Denier and St\''ephane Ducasse and Alexandre Bergel},
  booktitle = {WCRE ''09: Proceedings of the 2009 16th Working Conference on Reverse Engineering},
  year = {2009},
  keywords     = {moose-pub lse-pub},
  aeres	       = {ACT},
  misc	       = {Acceptance rate: 20/79 = 25\%},
  rate	       = {25\%},
  annote = {internationalconference},
  aeresstatus  = {aeres12},
  labo         = {dans},
  inria	       = {rmod},
  selectif     = {oui},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@inproceedings{Lava09d,
  title = {Identifying cycle causes with CycleTable},
  author = {Jannik Laval and Simon Denier and St\''ephane Ducasse},
  booktitle = {FAMOOSr 2009: 3rd Workshop on FAMIX and MOOSE in Software Reengineering},
  year = {2009},
  keywords     = {moose-pub lse-pub},
  aeres	       = {ACT},
  annote = {internationalworkshop},
  aeresstatus  = {aeres12},
  labo		   = {dans},
  inria	       = {rmod},
  selectif     = {non},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@book{Leru06a,
	author = {Ierusalimschy, R},
	title = {programming in Lua},
	publisher = {lua.org},
	year = {2006}
}

@book{Liu96a,
 author = {Chamond Liu},
 title = {Smalltalk, objects, and design},
 year = {1996},
 isbn = {0-13-268335-0},
 publisher = {Prentice-Hall, Inc.},
 address = {Upper Saddle River, NJ, USA}
}

@inproceedings{Lope05c,
 author = {Cristina Videira Lopes and Sushil Krishna Bajracharya},
 title = {An analysis of modularity in aspect oriented design},
 booktitle = {AOSD ''05: Proceedings of the 4th international conference on Aspect-oriented software development},
 year = {2005},
 isbn = {1-59593-042-6},
 pages = {15--26},
 location = {Chicago, Illinois},
 doi = {10.1145/1052898.1052900},
 publisher = {ACM},
 address = {New York, NY, USA}
}

@book{Lore94a,
  Author       = {Mark Lorenz and Jeff Kidd},
  Isbn	       = {13-179292-X},
  Keywords     = {oobib(gen) book scglib oorp},
  Publisher    = {Prentice-Hall},
  Title	       = {Object-Oriented Software Metrics: {A} Practical
                  Guide},
  Year	       = {1994}
}

@book{Lutz01a,
  Author       = {Mark Lutz},
  Isbn	       = {0596000855},
  Keywords     = {scglib},
  Publisher    = {O''Reilly \& Associates, Inc.},
  Title	       = {Programming {Python} (2nd edition)},
  Year	       = {2001}
}

@article{Lutz01b,
    title = {Evolving good hierarchical decompositions of complex systems},
    address = {School of Cognitive and Computing Sciences, University of Sussex, Falmer, Brighton BN1 9QH, UK},
    author = {Rudi Lutz},
    doi = {10.1016/S1383-7621(01)00019-4},
    journal = {Journal of Systems Architecture},
    keywords = {Software-Decomposition, Hierarchies-Abstraction},
    number = {7},
    pages = {613--634},
    volume = {47},
    year = {2001}
}

 @article{MacC06a,
 author = {Alan MacCormack and John Rusnak and Carliss Y. Baldwin},
 title = {Exploring the Structure of Complex Software Designs: An Empirical Study of Open Source and Proprietary Code},
 journal = {Management Science},
 volume = {52},
 number = {7},
 year = {2006},
 issn = {0025-1909},
 pages = {1015--1030},
 doi = {10.1287/mnsc.1060.0552},
 publisher = {INFORMS},
 address = {Institute for Operations Research and the Management Sciences (INFORMS), Linthicum, Maryland, USA}
 }

@book{Made08a,
	author = {Mader, Stewart},
	title = {Wikipatterns},
	publisher = {Wiley},
	year = {2008}
}

 @article{Madh92a,
 author = {Madhavji, Nazim H.},
 title = {Environment Evolution: The Prism Model of Changes},
 journal = {IEEE Transaction in Software Engineering},
 volume = {18},
 number = {5},
 year = {1992},
 issn = {0098-5589},
 pages = {380--392},
 doi = {10.1109/32.135771}
 }

@book{Manu06a,
	author = {Manulescu},
	title = {Patterns languages of programm design 5},
	publisher = {Wiley},
	year = {2006}
}

@inproceedings{Mark07a,
 	author = {Mark Harman},
 	title = {The Current State and Future of Search Based Software Engineering},
 	booktitle = {FOSE ''07: 2007 Future of Software Engineering},
	year = {2007},
	isbn = {0-7695-2829-5},
	pages = {342--357},
	doi = {10.1109/FOSE.2007.29},
	publisher = {IEEE Computer Society},
	address = {Washington, DC, USA},
	 Keywords = {Optimization-techniques}
}

@misc{Mart02c,
 author = {Robert C. Martin},
 note	 = {www.objectmentor.com},
 title = {SRP: The Single Responsibility Principle},
 url	= {http://www.objectmentor.com/resources/articles/srp.pdf},
 year	 = {2002}
}

@misc{Mart05c,
 author = {Robert C. Martin},
 note	 = {Software Development},
 title = {The Tipping Point: Stability and Instability in OO Design},
 url	= {http://www.ddj.com/architect/184415285},
 year	 = {2005}
}

@misc{Mart94c,
 author = {Robert C. Martin},
 note	 = {www.objectmentor.com},
 title = {OO Design Quality Metrics},
 url	= {http://www.objectmentor.com/resources/articles/oodmetrc.pdf},
 year	 = {1994}
}

@article{Mens04b,
 author = {Mens, Tom and Tourw\''{e}, Tom},
 title = {A Survey of Software Refactoring},
 journal = {IEEE Transaction on Software Engineering},
 volume = {30},
 number = {2},
 year = {2004},
 issn = {0098-5589},
 pages = {126--139},
 doi = {10.1109/TSE.2004.1265817},
 publisher = {IEEE Press},
 address = {Piscataway, NJ, USA}
 }

@book{Meye88b,
  Author       = {Bertrand Meyer},
  Keywords     = {olit-oopl eiffel oobib(oopl) scglib},
  Publisher    = {Prentice-Hall},
  Title	       = {Object-oriented Software Construction},
  Year	       = {1988}
}

@book{Mile06a,
	author = {Miles},
	title = {Learning UML 2.0},
	publisher = {O''Reilly},
	year = {2006}
}

@book{Mirk04a,
	author = {Mirkim},
	title = {Computer security},
	publisher = {Kluwer Academic Publishers},
	year = {2004},
	note = {received, Suen}
}

@book{Mitc03a,
  Author       = {John C. Mitchell},
  Isbn	       = {0-521-78098-5},
  Keywords     = {scglib},
  Publisher    = {Cambridge University Press},
  Title	       = {Concepts in Programming Languages},
  Year	       = {2003}
}

@inproceedings{Mord09a,
  author       = {Karine Mordal-Manet and Fran\cc oise Balmas and Simon Denier and St\''ephane Ducasse and Harald Wertz and Jannik Laval and Fabrice Bellingard and Philippe Vaillergues},
  title	       = {The Squale Model -- A Practice-based Industrial Quality Model},
  annote       = {internationalconference},
  booktitle    = {ICSM ''09: Proceedings of the IEEE International Conference on Software Maintenance},
  abstract     = {},
  Misc	       = {acceptance rate: 35(+29)/162: 21(40)\% for short papers},
  rate	       = {21\%},
  keywords     = {squale-pub lse-pub},
  aeres	       = {ACT},
  aeresstatus  = {aeres12},
  selectif     = {oui},
  inria	       = {dans},
  pages	       = {94--103},
  keywords     = {moose-pub},
  year	       = {2009},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@techreport{Mord09b,
  author       = {Karine Mordal-Manet and Fran\cc oise Balmas and Simon Denier and St\''ephane Ducasse and Harald Wertz and Jannik Laval and Fabrice Bellingard and Philippe Vaillergues},
  title	       = {The Squale Model -- A \emph{Practice-}based Industrial Quality Model},
  keywords     = {squale-pub lse-pub},
  annote       = {technicalReport stefPub},
  institution  = {INRIA Lille Nord Europe},
  year	       = {2009}
}

@book{Murp85a,
	Author = {Raymond Murphy},
	Title = {English Grammar in Use},
	Publisher = {Cambridge University Press},
	ISBN = {0-521-28723},
	Year = {1985}
}

@book{Nobl99a,
 	Author = {James Noble and Antero Taivalsaari and Ivan Moore},
	Title = {Prototype-Based Programming},
	Publisher = {Springer},
	Year = {1999}
}

@book{Norm98a,
	Author = {Donald A. Norman},
	Title = {The Design of Everyday Things},
	Year = {1998},
	ISBN = {0-262-64037-6 	978-0-262-64037-4},
	Publisher = {The MIT Press}
}

@book{Oaks01a,
	author = {Oaks},
	title = {Java security},
	publisher = {O''Reilly},
	year = {2001},
	note = {received, Suen}
}

@mastersthesis{Peirs08a,
  author       = {Romain Peirs},
  title	       = {Enhanced Dependency Structure Matrix},
  year	       = {2008},
  abstract     = {Dependency Structure Matrix (DSM) is an approach taken from
                  process optimization and it exists a variety of algorithms
                  to help organizing the matrix in a form that reflects the
                  architecture and highlights patterns and problematic
                  dependencies. However, the existing DSM implementations have
                  a lack of information in their visualization. That is why, we
                  enhanced DSM by adding written and colored information in the
                  visualization to improve the architecture understanding of a
                  software system and the support of its remodularization. This
                  visualization has been implemented on top of Moose which is a
                  collaborative research platform for Software Analysis and
                  Information Visualization. This report presents my
                  internship done at the research centre INRIA Lille - Nord
                  Europe with the RMoD Team led by S. Ducasse.},
  annote       = {master cook},
  school       = {Enseita}
 }

@inproceedings{Piess09a,
  title={Security Monitor Inlining for Multithreaded Java },
  author={Dam, Mads and Jacobs, Bart and Lundblad, Andreas and Piessens, Frank},
  booktitle={ECOOP edition:23 location:Genova date:6-10 July 2009},
  publisher    = {Springer-Verlag},
  year={2009},
  moth={jul},
  inria= {hors}
}

@inproceedings{Pour07a,
	author =  {Frederic Pourraz and Herve Verjus},
	title = {Diapason: an Engineering Environment for Designing, Enacting and Evolving Service-Oriented Architectures},
	booktitle = {International Conference on Software Engineering Advances (ICSEA 2007)},
	 publisher = {IEEE Computer Society},
	year = {2007}}

@inproceedings{Pour07b,
	author =  {Frederic Pourraz and Herve Verjus},
	title = {Diapason: an Engineering Environment for Designing, Enacting and Evolving Service-Oriented Architectures},
	booktitle = {International Conference on Software Engineering Advances (ICSEA 2007)},
	publisher = {IEEE Computer Society},
	pages = {23-30},
	year = {2007}
}

@inbook{Pour08a,
	author = {Frederic Pourraz and Herve Verjus},
	title = {Managing Service-Based EAI Architectures Evolution Using a Formal Architecture-Centric Approach},
	booktitle = {Enterprise Information Systems VIII},
	publisher = {Springer-Verlag},
	pages = {269-280},
	year = {2008}}

@book{Rask00a,
author = {Jef Raskin},
title = {The humane interface: new directions for designing interactive systems},
year = {2000},
isbn = {0-201-37937-6},
publisher = {ACM Press/Addison-Wesley Publishing Co.},
address = {New York, NY, USA}
}

@book{Ravi03a,
 author = {C. Ravindranath Pandian},
 title = {Software Metrics: A Guide to Planning, Analysis, and Application},
 year = {2003},
 isbn = {0849316618},
 publisher = {CRC Press, Inc.},
 address = {Boca Raton, FL, USA}
}

@inproceedings{Raza09a,
	title={Multiple Viewpoints Architecture Extraction},
	year = {2009},
	author = {Azadeh Razavizadeh and Sorana C\^impan and Herv\''e Verjus and St\''ephane Ducasse},
	booktitle = {Proceedings of the 2009 Joint Working IEEE/IFIP Conference on Software Architecture & European Conference on Software Architectures},
	annote ={internationalconference},
	pages    = {329--332},
        aeres	  = {ACT},
        aeresstatus  = {aeres12},
        labo = {dans},
        keywords = {moose-pub lse-pub},
        inria = {RMOD},
        x-editorial-board = {yes},
        x-proceedings = {yes},
        x-international-audience = {yes}
}

@inproceedings{Raza09b,
	title={Software System Understanding via Architectural Views Extraction According to Multiple Viewpoints },
	year = {2009},
	author = {Azadeh Razavizadeh and Sorana C\^impan and Herv\''e Verjus and St\''ephane Ducasse},
	booktitle      = {8th International Workshop on System/Software Architectures},
	annote       = {internationalworkshop},
    aeres	       = {ACT},
    aeresstatus    = {aeres12},
     keywords = {moose-pub lse-pub},
    inria	       = {RMOD},
    labo = {hors},
     x-editorial-board = {yes},
     x-proceedings = {yes},
     x-international-audience = {yes}
}

@inproceedings{Ren04a,
   author = {Xiaoxia Ren and Fenil Shah and Frank Tip and Barbara Ryder	and Ophelia Chesley},
   title = {Chianti: A tool for change impact analysis of {J}ava programs},
   booktitle = {Object-Oriented Programming Systems, Languages, and	Applications (OOPSLA 2004)},
   pages = {432--448},
   address = {Vancouver, BC, Canada},
   month = {oct},
   year = {2004}
}

@book{Repp99a,
  Author       = {John H. Reppy},
  Keywords     = {ml scglib},
  Publisher    = {Cambridge University Press},
  Title	       = {Concurrent Programming in ML},
  Year	       = {1999}
}

@book{Riel96a,
  Address      = {Boston MA},
  Author       = {Arthur Riel},
  Keywords     = {scglib oorp},
  Pages	       = {400},
  Publisher    = {Addison Wesley},
  Title	       = {Object-Oriented Design Heuristics},
  Year	       = {1996}
}

@inproceedings{Roet09a,
  Author       = {David R\"{o}thlisberger and Oscar Nierstrasz and St\''ephane Ducasse and Damien Pollet and Romain Robbes},
  Keywords     = {scg-pub snf09 jb09 roethlisberger},
  Annote       = {internationalconference},
  Title	       = {Supporting Task-oriented Navigation in {IDEs} with Configurable HeatMaps},
  Abstract     = {Mainstream IDEs generally rely on the static structure of a
  		software project to support browsing and navigation.
		We propose HeatMaps, a simple but highly configurable technique
		to enrich the way an IDE displays the static structure of a software
		system with additional kinds of information.
		A heatmap highlights software artifacts according to various metric values,
		such as bright red or pale blue, to indicate their potential degree of interest.
		We present a prototype system that implements heatmaps, and we describe
		an initial study that assesses the degree to which different heatmaps effectively
		guide developers in navigating software.},
  peer	       = {yes},
  x-pays       = {Switzerland},
  Booktitle    = {Proceedings of the 17th International Conference on
                  Program Comprehension (ICPC 2009)},
  Publisher    = {IEEE Computer Society},
  Address      = {Los Alamitos, CA, USA},
  Journal      = {icpc},
  Pages	       = {253--257},
  Isbn	       = {978-0-7695-3176-2},
  Doi	       = {10.1109/ICPC.2008.32},
  Url	       = {http://scg.unibe.ch/archive/papers/Roet09aHeatMapsICPC2009.pdf},
  Year	       = {2009},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@techreport{Roet09d,
  Abstract     = {Mainstream IDEs generally rely on the static structure of a
  		software project to support browsing and navigation.
		We propose HeatMaps, a simple but highly configurable technique
		to enrich the way an IDE displays the static structure of a software
		system with additional kinds of information.
		A heatmap highlights software artifacts according to various metric values,
		such as bright red or pale blue, to indicate their potential degree of interest.
		We present a prototype system that implements heatmaps, and we describe
		an initial study that assesses the degree to which different heatmaps effectively
		guide developers in navigating software.},
  Address      = {Universit\"at Bern, Switzerland},
  Author       = {David R\"{o}thlisberger and Oscar Nierstrasz and St\''ephane Ducasse and Damien Pollet and Romain Robbes},
  Classification= {D.2.2 Tools and Techniques; D.2.3  Coding; D.2.6 Programming Environments; D.2.9 Management},
  General_Terms= {Coding, Programming Environments, Program Editors, Integrated Environments},
  Institution  = {Institut f\"ur Informatik},
  Keywords     = {scg-pub snf09 jb09 roethlisberger},
  Month	       = jul,
  Number       = {IAM-09-005},
  annote       = {technicalreport},
  Title	       = {Supporting Task-oriented Navigation in {IDEs} with Configurable HeatMaps},
  Type	       = {Technical Report},
  Url	       = {http://scg.unibe.ch/archive/papers/Roet09dHeatMapsTechReport.pdf},
  Year	       = {2009}
}

@inproceedings{Roet09e,
  Title	       = {Tackling Software Navigation Issues of the Smalltalk IDE},
  Abstract     = {The IDE used in most Smalltalk dialects such as Pharo, Squeak or Cincom Smalltalk did not evolve
  			significantly over the last years, if not to say decades. For other languages, for instance Java, the
			available IDEs made tremendous progress as Eclipse or NetBeans illustrate. While the Smalltalk
			IDE served as an exemplar for many years, other IDEs caught up or even overtook the erstwhile
			leader in terms of feature-richness, usability, or code navigation facilities.
			In this paper we first analyze the difficulty of software navigation in the Smalltalk IDE and second
			illustrate with concrete examples the features we added to the Smalltalk IDE to fill the gap to
			modern IDEs and to provide novel, improved means to navigate source space. We show that
			thanks to the agility and dynamics of Smalltalk, we are able to extend and enhance with reasonable
			effort the Smalltalk IDE to better support software navigation, program comprehension, and software
			maintenance in general. One such support is the integration of dynamic information into the static
			source views we are familiar with. Other means include easing the access to static information
			(for instance by better arranging important packages) or helping developers re-locating artifacts
			of interest (for example with a categorization system such as smart groups).},
  Annote       = {internationalworkshop},
  x-pays       = {Switzerland},
  Author       = {David R\"{o}thlisberger and Oscar Nierstrasz and St\''ephane Ducasse and Alexandre Bergel},
  Booktitle    = {Proceedings of International Workshop on Smalltalk Technologies (IWST 2009)},
  Peer	       = {yes},
  Keywords     = {scg-sub jb10 roethlisberger remoose2-pub},
  Location     = {Brest, France},
  Publisher    = {ACM Digital Library},
  Year	       = {2009},
  aeres	       = {ACT},
  aeresstatus  = {aeres12},
  selectif     = {non},
  labo         = {dans},
  inria	       = {RMOD},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}

}

@inproceedings{Roet09f,
  Author       = {David R\"{o}thlisberger and Oscar Nierstrasz and St\''ephane Ducasse},
  Keywords     = {snf09 jb10 roethlisberger remoose2-pub},
  Annote       = {internationalconference},
  Title	       = {Autumn Leaves: Curing the Window Plague in IDEs},
  Abstract     = {Navigating large software systems is difficult as the various artifacts are distributed in a huge space,
  			while the relationships between different artifacts often remain hidden and obscure. As a consequence,
			developers using a modern interactive development environment (IDE) are forced to open views
			on numerous source artifacts to reveal these hidden relationships, leading to a crowded workspace
			with many opened windows or tabs.
			Developers often lose the overview in such a cluttered workspace as IDEs provide little support to
			get rid of unused windows. AutumnLeaves automatically selects windows unlikely for future use
			to be closed or grayed out while important ones are displayed more prominently.
			This reduces the number of windows opened at a time and adds structure to the developer''s workspace.
			We validate AutumnLeaves with a benchmark evaluation using recorded navigation data of various
			developers to determine the prediction quality of the employed algorithms.},
  peer	       = {yes},
  Booktitle    = {Proceedings of the 16th Working Conference on Reverse Engineering (WCRE 2009)},
  Publisher    = {IEEE Computer Society},
  Address      = {Los Alamitos, CA, USA},
  x-pays       = {Switzerland},
  aeres	       = {ACT},
  misc	       = {Acceptance rate: 20/79 = 25\%},
  rate	       = {25\%},
  aeresstatus  = {aeres12},
  selectif     = {non},
  inria	       = {RMOD},
  labo         = {dans},
  Location     = {Lille, France},
  Year	       = {2009},
  x-editorial-board = {yes},
  x-proceedings = {yes},
  x-international-audience = {yes}
}

@techreport{Rudi00a,
    author = {Rudi Lutz},
    institution  = {School of Cognitive and Computing Sciences University of Sussex -- England},
    title = {Evolving Good Hierarchical Decompositions of Complex System},
    year = {2000},
    keywords = {Evolutive-Algorithms Genetic-Algorithms  Subsystem-Decomposition Hierarchical-Decompositions}
}

@article{Sarg64a,
  title={"Speed-up" in Chemical Engineering Design},
  author={Sargent, P.R.W.H. and Westerberg, AW},
  journal={Chemical Engineering Research and Design},
  volume={42},
  number={a},
  pages={190--197},
  year={1964},
  publisher={ICHemE}
}

@book{Schm00a,
  Author       = {Douglas C. Schmidt and Michael Stal and Hans Rohnert  and Frank Buschmann},
  Keywords     = {oorp},
  Publisher    = {John Wiley and Sons},
  Title	       = {Pattern-Oriented Software Architecture Volume 2 --- Networked and Concurrent Objects},
  Year	       = {2000}
}

@book{Schw01a,
  Author       = {Ken Schwaber and Mike Beedle},
  Edition      = {First},
  Isbn	       = {0-13-067634-9},
  Keywords     = {book scglib},
  Publisher    = {Alan R. Apt},
  Title	       = {Agile Software Development with Scrum},
  Year	       = {2001}
}

@book{Scot06a,
	author = {Scott, Michael L},
	title = {Programming language pragmatics},
	publisher = {lua.org},
	year = {2006}
}

@inproceedings{Seng05a,
 	author = {Olaf Seng and Markus Bauer and Matthias Biehl and Gert Pache},
 	title = {Search-based improvement of subsystem decompositions},
 	booktitle = {GECCO ''05: Proceedings of the 2005 conference on Genetic and evolutionary computation},
 	year = {2005},
 	isbn = {1-59593-010-8},
 	pages = {1045--1051},
	location = {Washington DC, USA},
 	doi = {10.1145/1068009.1068186},
 	publisher = {ACM},
 	address = {New York, NY, USA},
 	Keywords = {Evolutive-Algorithms Genetic-Algorithms  Subsystem-Decomposition Subsystem-Improvement}
 }

@article{Serb07c,
title={Restructuring software systems using clustering},
author={G. Serban and l. G. Czibula},
journal={22nd international symposium on Computer and information sciences (ISCIS''07).},
year={2007},
month={nov},
pages={1-6},
keywords={pattern clustering, software maintenance, software quality, clustering techniques, k-medoids based clustering algorithm, refactoring software systems, restructuring software systems},
doi={10.1109/ISCIS.2007.4456872}
}

@inproceedings{Shao07a,
	author= {D. Shao and S. Khurshid  and D.E. Perry},
	title = {Evaluation of semantic interference detection in parallel changes: an exploratory experiment},
	booktitle ={Proceedings of the 23rd IEEE International Conference. on Software Maintenance (ICSM''07)},
	month ={oct},
	year = {2007},
	pages ={74--83}
}

@inproceedings{Shao09a,
	title = {SCA: a Semantic Conflict Analyzer for Parallel Changes},
	author = {Danhua Shao and Sarfraz Khurshid and Dewayne E. Perry},
	booktitle ={Proceedings of ESEC/FSE''09},
	year = {2009}
}

@book{Smit05b,
  Author       = {James E. Smith and Ravi Nair},
  Isbn	       = {1-55860-910-5},
  Publisher    = {Morgan Kaufmann},
  Title	       = {Virtual Machines},
  Year	       = {2005}
}

@book{Spen01a,
	author={Robert Spence},
	title={Information Visualization},
	year={2001},
	publisher={Adisson-Wesley}
}

@book{Spri89a,
 author = {George Springer and Daniel P. Friedman},
 title = {Scheme and the art of programming},
 year = {1989},
 isbn = {0-262-19288-8},
 publisher = {MIT Press},
 address = {Cambridge, MA, USA}
}

@inproceedings{Stei06a,
    author = {Friedrich Steimann},
    title = {The Paradoxical Success of Aspect-Oriented Programming},
    booktitle = {OOPSLA},
    location = {Portland},
    publisher = {ACM Press},
    month = oct,
    year = {2006}
}

@article{Stew81a,
  title={The design structure matrix: A method for managing the design of complex systems},
  author={Steward, D.},
  journal={IEEE Transactions on Engineering Management},
  volume={28},
  number={3},
  pages={71--74},
  year={1981}
}

@book{Stro90a,
  Author       = {Bjarne Stroustrup and Magaret A. Ellis},
  Isbn	       = {0-201-51459-1},
  Keywords     = {olit-oopl c++ oobib(oopl) book scglib},
  Publisher    = {Addison Wesley},
  Title	       = {The Annotated {C}++ Reference Manual},
  Year	       = {1990}
}

@book{Stro97a,
  Author       = {Bjarne Stroustrup},
  Edition      = {Third},
  Isbn	       = {0-201-88954-4},
  Keywords     = {c++},
  Publisher    = {Addison Wesley},
  Title	       = {The {C}++ Programming Language},
  Year	       = {1997}
}

@inproceedings{Swif01a,
    author = {X Liu and S Swift and A Tucker},
    title = {Using evolutionary algorithms to tackle large scale grouping problems},
    booktitle = {In GECCO 2001: Proceedings of the Genetic and Evolutionary Computation Conference},
    year = {2001},
    Keywords = {Evolutive-Algorithms Genetic-Algorithms  Subsystem-Decomposition}
}

@book{Taka04a,
	author = {Takao Nishizeki and Md Saidur Rahman},
	title = {Planar Graph Drawing},
	publisher = {World Scientific},
	year = {2004},
	note = {received 10-06-2009, library}
}

@inproceedings{Thio05a,
   title={Parallel Changes: Detecting Semantic Interferences},
   author = {Gian Lorenzo Thione and Dewayne E. Perry},
   booktitle ={International Computer Software and Applications Conference (COMPSAC 2005)},
   year ={2005}
}

@book{Thom05a,
  Author       = {David Thomas and Andy Hunt},
  Edition      = {2nd},
  Keywords     = {scglib ruby},
  Publisher    = {Addison Wesley},
  Title	       = {Programming Ruby},
  Year	       = {2005}
}

@book{Thom99a,
  Address      = {Reading, Mass.},
  Author       = {Simon Thompson},
  Isbn	       = {0201342758},
  Publisher    = {Addison Wesley},
  Title	       = {Haskell: The Craft of Functional Programming (2nd edition)},
  Year	       = {1999}
}

@article{Tip95a,
      author= {Frank Tip},
      title= {A survey of program slicing techniques},
      journal = {Journal of Programming Languages},
      volume = {3},
      year = {1995},
      pages = {121--189}
}

@book{Tuft06a,
 author = {Edward R. Tufte},
 title = {Beautiful evidence},
 year = {2006},
 isbn = {0-961392177},
 publisher = {Graphics Press},
 address = {Cheshire, CT, USA}
}

@book{Tuft06b,
 author = {Edward R. Tufte},
 title = {Cognitive Style of Powerpoint: Pitching Out Corrupts Within},
 year = {2006},
 isbn = {0-961392169},
 publisher = {Graphics Press},
 address = {Cheshire, CT, USA}
}

@book{Tuft86a,
 author = {Edward R. Tufte},
 title = {The visual display of quantitative information},
 year = {1986},
 isbn = {0-9613921-0-X},
 publisher = {Graphics Press},
 address = {Cheshire, CT, USA}
}

@book{Tuft90a,
 author = {Edward Tufte},
 title = {Envisioning information},
 year = {1990},
 isbn = {0-9613921-1-8},
 publisher = {Graphics Press},
 address = {Cheshire, CT, USA}
}

@book{Tuft97a,
 author = {Edward R. Tufte},
 title = {Visual explanations: images and quantities, evidence and narrative},
 year = {1997},
 isbn = {0-9613921-2-6},
 publisher = {Graphics Press},
 address = {Cheshire, CT, USA}
}

@book{Tuft97b,
 author = {Edward R. Tufte},
 title = {Visual \& Statistical Thinking: Displays of Evidence for Decision Making},
 year = {1997},
 isbn = {0-961392134},
 publisher = {Graphics Press},
 address = {Cheshire, CT, USA}
}

@article{Tzer97f,
author = {Vassilios Tzerpo and R. C. Holt},
title = {The Orphan Adoption Problem in Architecture Maintenance},
journal ={Reverse Engineering, Working Conference on},
volume = {0},
year = {1997},
isbn = {0-8186-8162-4},
pages = {76},
doi = {10.1109/WCRE.1997.624578},
publisher = {IEEE Computer Society},
address = {Los Alamitos, CA, USA}
}

@inproceedings{Vano08a,
 author= {Vanoverberghe, Dries and Piessens, Frank},
 title = {A caller-side inline reference monitor for an Object-Oriented intermediate language},
 booktitle = {Formal Methods for Open Object-based Distributed Systems},
 series = {LNCS 5051},
 year = {2008},
 pages = {240--258}
}

@techreport{Verj06a,
  Author       = {Herve Verjus},
  Institution  = {Technical Report 06/03, LISTIC --- Universit\''e de Savoie},
  Title	       = {Nimrod: A Software Architecture Engineering Environment},
  Year	       = {2006}
}

@inproceedings{Verj06b,
	author ={Herve Verjus and  Sorana C\^impan and Ilham Alloui and Flavio Oquendo},
	title = {Gestion des architectures \''evolutives dans ArchWare},
	booktitle = {1\`ere conf. francophone sur les architectures logicielles (CAL)},
	year = {2006}
}

@book{Ware00a,
 author = {Colin Ware},
 title = {Information visualization: perception for design},
 year = {2000},
 isbn = {1-55860-511-8},
 publisher = {Morgan Kaufmann Publishers Inc.},
 address = {San Francisco, CA, USA}
}

@article{Warf73a,
  title={Binary Matrices in System Modeling},
  author={Warfield, J.N.},
  journal={IEEE Transactions on Systems, Man, and Cybernetics},
  volume={3},
  number={5},
  pages={441--449},
  year={1973}
}

@article{Wels84a,
    author= {M. Welser},
	title = {Program Slicing},
	journal= {IEEE Transactions on Software Engineering},
	publisher= {IEEE Computer Society},
	year = {1984},
	pages = {352--357}
}

@book{Winst98a,
  Author       = {Patrick Henry Winston},
  Keywords     = {smalltalk scglib},
  Publisher    = {Addison Wesley},
  Title	       = {On to {Smalltalk}},
  Year	       = {1998}
}

@book{Wirf03a,
  Author       = {Rebecca Wirfs-Brock and Alan McKean},
  Isbn	       = {0-201-37943-0},
  Publisher    = {Addison-Wesley},
  Title	       = {Object Design --- Roles, Responsibilities and Collaborations},
  Year	       = {2003}
}

@book{Witt00a,
  Author       = {Ian Witten and Eibe Frank},
  Isbn	       = {1-55860-552-5},
  Keywords     = {scglib},
  Publisher    = {Morgan Kauffmann},
  Title	       = {Data Mining},
  Year	       = {2000}
}

@book{Wohl00a,
 author = {Claes Wohlin and Per Runeson and Martin H\"{o}st and Magnus C. Ohlsson and Bj\"{o}orn Regnell and Anders Wessl\''{e}n},
 title = {Experimentation in software engineering: an introduction},
 year = {2000},
 isbn = {0-7923-8682-5},
 publisher = {Kluwer Academic Publishers},
 address = {Norwell, MA, USA}
}

@book{Wu04a,
	author = {Wu and Weili},
	title = {Clustering and information retrieval},
	publisher = {Kluwer Academic Publishers},
	year = {2004}
}

@article{Yass99a,
  title={Engineering design management: an information structure approach},
  author={Yassine, A. and Falkenburg, D. and Chelst, K.},
  journal={International Journal of Production Research},
  volume={37},
  number={13},
  pages={2957--2975},
  year={1999},
  publisher={Taylor \& Francis}
}

@book{Yoko90a,
  Author       = {Yasuhiko Yokote},
  Keywords     = {smalltalk concurrentsmalltalk scglib},
  Publisher    = {World Scientific},
  Series       = {World Scientific Series in Computer Science},
  Title	       = {The Design and Implementation of
                  {Concurrent}{Smalltalk}},
  Volume       = {21},
  Year	       = {1990}
}

@book{Yone87a,
  Address      = {Cambridge, Mass.},
  Author       = {Akinori Yonezawa and Mario Tokoro},
  Isbn	       = {0-262-24026-2},
  Keywords     = {olit-obc oobib(obcp) book scglib},
  Publisher    = {MIT Press},
  Title	       = {Object-Oriented Concurrent Programming},
  Year	       = {1987}
}

@book{Zell05a,
  Author       = {Andreas Zeller},
  Isbn	       = {1558608664},
  Keywords     = {testing},
  Month	       = oct,
  Publisher    = {Morgan Kaufmann},
  Title	       = {Why Programs Fail: A Guide to Systematic Debugging},
  Year	       = {2005}
}


@inproceedings{Zhan08a,
    author ={Sai Zhang and Zhongxian Gu and Yu Lin and Jianjun Zhao},
    title ={Change Impact Analysis for AspectJ Programs},
    booktitle = {Proceedings of the International Conference on Software Maintenance},
    year ={2008}
}

@inproceedings{Zhou08a,
author={Tianlin Zhou and Baowen Xu and Liang Shi and Yuming Zhou and Lin Chen},
title={Measuring Package Cohesion Based on Context},
booktitle={IEEE International Workshop on Semantic Computing and Systems, 2008. WSCS ''08.},
year={2008},
pages={127-132},
keywords={software metrics, software packages, package cohesion metrics, package quality},
doi={10.1109/WSCS.2008.23}
}'
]

{ #category : #data }
CZScriptTest class >> scgbibSample [
	^ '@inproceedings{Lien08b,
  author       = {Adrian Lienhard and Tudor G\^irba and Oscar
                  Nierstrasz},
  title	       = {Practical Object-Oriented Back-in-Time Debugging},
  abstract     = {Back-in-time debuggers are extremely useful tools
                  for identifying the causes of bugs, as they allow us
                  to inspect the past states of objects no longer
                  present in the current execution
                  stack. Unfortunately the "omniscient" approaches
                  that try to remember all previous states are
                  impractical because they either consume too much
                  space or they are far too slow. Several approaches
                  rely on heuristics to limit these penalties, but
                  they ultimately end up throwing out too much
                  relevant information. In this paper we propose a
                  practical approach to back-in-time debugging that
                  attempts to keep track of only the relevant past
                  data. In contrast to other approaches, we keep
                  object history information together with the regular
                  objects in the application memory. Although
                  seemingly counter-intuitive, this approach has the
                  effect that past data that is not reachable from
                  current application objects (and hence, no longer
                  relevant) is automatically garbage collected. In
                  this paper we describe the technical details of our
                  approach, and we present benchmarks that demonstrate
                  that memory consumption stays within practical
                  bounds. Furthermore since our approach works at the
                  virtual machine level, the performance penalty is
                  significantly better than with other approaches.},
  annote       = {internationalconference},
  Note	       = {ECOOP distinguished paper award},
  peer	       = {yes},
  keywords     = {scg-pub object-flow snf08 jb08 girba},
  Publisher    = {Springer},
  Series       = {LNCS},
  Volume       = {5142},
  Url	       = {http://scg.unibe.ch/archive/papers/Lien08bBackInTimeDebugging.pdf
                  http://www.springerlink.com/content/v178515tx1q25823/},
  Doi	       = {10.1007/978-3-540-70592-5_25},
  ISBN	       = {978-3-540-70591-8},
  booktitle    = {Proceedings of the 22nd European Conference on
                  Object-Oriented Programming (ECOOP''08)},
  Pages	       = {592--615},
  year	       = {2008}
}

@techreport{Bung09a,
  Abstract     = {
		Browsers are a crucial instrument to understand complex systems or models. Each problem
		domain is accompanied by an abundance of browsers that are created to help analyze and
		interpret the underlying elements. The issue with these browsers is that they are frequently
		rewritten from scratch, making them expensive to create and burdensome to maintain.
		While many frameworks exist to ease the development of user interfaces in general, they
		provide only limited support to simplifying the creation of browsers.
		In this thesis we present a dedicated model to describe browsers that equally emphasizes
		the control of navigation flow within the browser. Our approach is designed to support
		arbitrar y domain models allowing researchers to quickly define new browsers for their data.
		To validate our model we have implemented the framework Glamour which additionally
		offers a declarative language to simplify the definition of browsers. We have used Glamour
		to re-implement several existing browsers and to explore the creation of new browsers.},
  Author       = {Philipp Bunge},
  Institution  = {University of Bern},
  Keywords     = {snf10 scg-msc jb09 moose-pub},
  Month	       = apr,
  Title	       = {Scripting	Browsers with {Glamour}},
  School       = {University of Bern},
  Type	       = {Master''s Thesis},
  Url	       = {http://scg.unibe.ch/archive/masters/Bung09a.pdf},
  Year	       = {2009}
}


@book{Huch05a,
  Annote       = {editor proceedings},
  Editor       = {Marianne Huchard and St\''ephane Ducasse and Oscar Nierstrasz},
  Isbn	       = {2-7462-1125-4},
  Keywords     = {book scglib stefPub},
  Publisher    = {Lavoisier},
  Series       = {L''objet},
  Title	       = {Langages et Mod\`eles \`a Objets LMO''05},
  Volume       = {11},
  Year	       = {2005}
}

@phdthesis{Deri97a,
  Author       = {Luca Deri},
  Keywords     = {snf-none olit scg-pub skipdoi skip-abstract
                  toBeChecked scg-phd jb97},
  Month	       = jun,
  School       = {University of Bern},
  Title	       = {A Component-based Architecture for Open,
                  Independently Extensible Distributed Systems},
  Type	       = {Ph.{D}. Thesis},
  Url	       = {http://scg.unibe.ch/archive/phd/deri-phd.pdf},
  Year	       = {1997}
}



@misc{PetitPetri,
  Abstract     = {Petri nets are a well-known mathematical formalism for
				modeling and reasoning about concurrency. This web page
                provides an overview of a Squeak Etoys implementation of a
                Petri net interpreter. First download and install Etoys and
                download Petit Petri. If you unzip the Petit Petri download you
                will find several Etoys project files containing examples that
                you can run. Simply start Etoys and drag and drop any of these
                files onto the running Etoys images.},
  Annote       = {misc},
  Author       = {Oscar Nierstrasz and Markus Gaelli},
  Keywords     = {scg-misc skipdoi petri nets etoys jb-none gaelli},
  Month	       = sep,
  Note	       = {\url{http://scg.unibe.ch/download/petitpetri}},
  Title	       = {Petit{Petri} --- A {Petri} Net Editor built with
                  {Etoys}},
  Url	       = {http://scg.unibe.ch/download/petitpetri},
  Year	       = {2005}
}

@mastersthesis{Reng06a,
  Abstract     = {Developing applications that end users can customize
                  is a challenge, since end users are domain experts
                  but still have concrete requirements. In this master
                  thesis we present how we used a meta-driven approach
                  to support the end user customization of Web
                  applications. We present Magritte, a recursive
                  meta-data meta-model integrated into the Smalltalk
                  reflective meta-model. The adaptive model of
                  Magritte enables to not only describe existing
                  classes but also let end users build their own
                  meta-models on the fly. Further on we describe how
                  meta-interpreters automatically build views,
                  reports, validating editors and persistency
                  mechanisms.  As a complete example of how we applied
                  a meta-model to a Web application we present Pier,
                  the second version of a fully object-oriented
                  implementation of a content management system and
                  Wiki engine. Pier is implemented with objects from
                  the top to the bottom and is designed to be
                  customizable to accommodate new needs. The
                  integration of a powerful meta-description layer
                  makes it a breeze to extend the running system with
                  new functionality without having to patch the core
                  engine.  We describe the lessons learned from using
                  the Magritte meta-model to build applications. Both
                  projects described in this thesis are open source
                  and can be downloaded from the Web site of the
                  author.},
  Author       = {Lukas Renggli},
  Keywords     = {scg-msc scg-pub skipdoi magritte pier jb06 fb06
                  snf06},
  Month	       = jun,
  School       = {University of Bern},
  Title	       = {{Magritte} --- Meta-Described Web Application
                  Development},
  Url	       = {http://scg.unibe.ch/archive/masters/Reng06a.pdf},
  Year	       = {2006}
}

@techreport{Ache98a,
  Author       = {Franz Achermann},
  Institution  = {IAM, U. Bern},
  Keywords     = {olit scg-wp piccola},
  Month	       = nov,
  Title	       = {JPict --- a framework for pi Agents},
  Type	       = {tech. note},
  Url	       = {http://www.iam.unibe.ch/~scg/Research/Piccola/History/jpict.pdf},
  Year	       = {1998}
}

@article{Duca06b,
  Abstract     = {Inheritance is well-known and accepted as a
                  mechanism for reuse in ob ject-oriented languages.
                  Unfortunately, due to the coarse granularity of
                  inheritance, it may be difficult to decompose an
                  application into an optimal class hierarchy that
                  maximizes software reuse. Existing schemes based on
                  single inheritance, multiple inheritance, or mixins,
                  all pose numerous problems for reuse. To overcome
                  these problems we propose traits, pure units of
                  reuse consisting only of methods. We develop a
                  formal model of traits that establishes how traits
                  can be composed, either to form other traits, or to
                  form classes. We also outline an experimental
                  validation in which we apply traits to refactor a
                  non-trivial application into composable units.},
  Annote       = {internationaljournal},
  Author       = {St\phane Ducasse and Oscar Nierstrasz and
                  Nathanael Sch{\"a}rli and Roel Wuyts and Andrew
                  Black},
  Cvs	       = {TraitsTOPLAS2005},
  Doi	       = {10.1145/1119479.1119483},
  Issn	       = {0164-0925},
  Journal      = {ACM Transactions on Programming Languages and
                  Systems (TOPLAS)},
  Keywords     = {scg-pub stefPub snf05 snf06 jb06 toplas traits
                  schaerli toplastraits},
  Misc	       = {SCI impact factor 1.404 (2005)},
  Miscmisc     = {was Duca05z},
  Month	       = mar,
  Number       = {2},
  pages	       = {331--388},
  aeres	       = {ACL},
  aeresstatus  = {aeres08},
  selectif     = {oui},
  inria	       = {hors},
  Title	       = {Traits: A Mechanism for fine-grained Reuse},
  Url	       = {http://scg.unibe.ch/archive/papers/Duca06bTOPLASTraits.pdf},
  Volume       = {28},
  Year	       = {2006}
}

'
]

{ #category : #old }
CZScriptTest >> createTestBibFile [
	"self new createTestBibFile"
	(FileDirectory default newFileNamed: self bibFileName)
		nextPutAll: (self scgbibSample copyReplaceAll: String cr with: String lf);
		close
]

{ #category : #resources }
CZScriptTest >> setUp [

	sc := CZScript new.
	sc bibStream: self class lseBibSample readStream.
	sc fillUpBibList.
]

{ #category : #resources }
CZScriptTest >> setUp2 [

	sc := CZScript new.
	sc bibStream: self class lseBibSample readStream.
	sc fillUpBibList.
]

{ #category : #resources }
CZScriptTest >> setUp3 [

	sc := CZScript new.
	sc bibStream: self class scgbibSample readStream.
	sc fillUpBibList.
]

{ #category : #tests }
CZScriptTest >> testAuthor [
	"self debug: #testAuthor"
	
	| dict |
	sc keepAuthor: 'Ducasse'.
	self deny: sc bibList isEmpty.
	dict := sc bibList groupedBy: [:each | each type].
	self assert: (dict at: #article) size = 4.
	self assert: (dict at: #book) size = 4.
	self assert: (dict at: #techreport) size = 6
]

{ #category : #tests }
CZScriptTest >> testAuthorBlackListed [
	"self debug: #testAuthorBlackListed"
	
	| dict |
	sc keepAuthor: 'Ducasse'.
	sc blackListedKeys: #(Balm09a).
	sc removeBlackList.
	self deny: sc bibList isEmpty.
	dict := sc bibList groupedBy: [:each | each type].
	self assert: (dict at: #article) size = 4.
	self assert: (dict at: #book) size = 4.
	self assert: (dict at: #inproceedings) size = 22.
	self assert: (dict at: #techreport) size = 5
	
]

{ #category : #tests }
CZScriptTest >> testAuthorEmptyBlackListed [
	"self debug: #testAuthorEmptyBlackListed"
	
	| dict |
	sc keepAuthor: 'Ducasse'.
	self deny: sc bibList isEmpty.
	dict := sc bibList groupedBy: [:each | each type].
	self assert: (dict at: #article) size = 4.
	self assert: (dict at: #book) size = 4.
	self assert: (dict at: #inproceedings) size = 22.
]

{ #category : #tests }
CZScriptTest >> testOriginalList [
	"self debug: #testOriginalList"
	
	self deny: sc originalBibs isEmpty.
	self assert: sc originalBibs size = 206.
]

{ #category : #tests }
CZScriptTest >> testWorkingList [
	"self debug: #testWorkingList"
	
	self deny: sc workingList isEmpty.
]
